// <auto-generated />
namespace ProvaTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionando_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionando_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "202112020311423_adicionando_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
