// <auto-generated />
namespace ProvaTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class criar_Inscricoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criar_Inscricoes));
        
        string IMigrationMetadata.Id
        {
            get { return "202112010213120_criar_Inscricoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
